deployment:
  tasks:
    - export SRCPATH=/home/contanet/repositories/contanet/
    - export DEPLOYPATH=/home/contanet/public_html/
    - /usr/bin/git -C $SRCPATH pull origin main
    - /usr/bin/rsync -av --delete --exclude=".git" $SRCPATH $DEPLOYPATH
    - echo "Deploy OK"
