---
deployment:
  tasks:
    - export DEPLOYPATH=/home/contanet/public_html/
    - export SRCPATH=/home/contanet/repositories/pagina/
    - /bin/rsync -av --delete --exclude=".git" --exclude=".cpanel.yml" $SRCPATH $DEPLOYPATH
